version: '3'

services:
  frontend:
    container_name: nextjs
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:8000/api}
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    external:
      true